import type { MetadataRoute } from 'next'

const SITE_URL = 'https://www.spanlens.io'

// Per-route lastmod dates. Bump when the page content materially changes so
// crawlers see real freshness signal instead of every URL sharing a single
// `new Date()`. Format: 'YYYY-MM-DD' (UTC).
const ROUTE_LASTMOD: Record<string, string> = {
  '': '2026-06-16',
  '/pricing': '2026-06-16',
  '/self-hosting': '2026-05-20',
  '/alternatives': '2026-06-01',
  '/changelog': '2026-06-15',
  '/feedback': '2026-04-10',
  '/faq': '2026-06-16',
  '/about': '2026-06-16',
  '/integrations/openai': '2026-06-16',
  '/integrations/anthropic': '2026-06-16',
  '/integrations/gemini': '2026-06-16',
  '/llm-observability': '2026-06-16',
  '/agent-tracing': '2026-06-16',
  '/llm-cost-tracking': '2026-06-16',
  '/pricing/gpt-4o': '2026-06-16',
  '/pricing/gpt-4o-mini': '2026-06-16',
  '/pricing/claude-3-5-sonnet': '2026-06-16',
  '/pricing/gemini-2-0-flash': '2026-06-16',
  '/pricing/o3-mini': '2026-06-16',
  '/tools/llm-cost-calculator': '2026-06-16',
  '/compare': '2026-06-01',
  '/compare/langfuse': '2026-06-10',
  '/compare/helicone': '2026-06-10',
  '/compare/langsmith': '2026-06-10',
  '/compare/braintrust': '2026-06-10',
  '/compare/arize-phoenix': '2026-06-10',
  '/docs/migrate/from-langfuse': '2026-05-25',
  '/docs/migrate/from-helicone': '2026-05-25',
  '/docs/migrate/from-langsmith': '2026-05-25',
  '/docs': '2026-06-12',
  '/docs/quick-start': '2026-06-12',
  '/docs/cli': '2026-06-12',
  '/docs/sdk': '2026-06-12',
  '/docs/proxy': '2026-06-08',
  '/docs/otel': '2026-06-08',
  '/docs/self-host': '2026-05-20',
  '/docs/why': '2026-06-01',
  '/docs/api': '2026-06-08',
  '/docs/api/errors': '2026-06-08',
  '/docs/concepts/data-model': '2026-05-15',
  '/docs/concepts/llm-observability': '2026-06-16',
  '/docs/concepts/agent-tracing': '2026-06-16',
  '/docs/concepts/evals': '2026-06-16',
  '/docs/concepts/prompt-management': '2026-06-16',
  '/docs/integrations/langgraph': '2026-06-12',
  '/docs/integrations/langchain': '2026-06-16',
  '/docs/integrations/crewai': '2026-06-16',
  '/docs/integrations/openai-assistants': '2026-06-16',
  '/docs/integrations/bedrock': '2026-06-16',
  '/docs/integrations/flowise': '2026-06-16',
  '/docs/integrations/instructor': '2026-06-16',
  '/docs/integrations/llamaindex': '2026-06-05',
  '/docs/integrations/mcp': '2026-06-04',
  '/docs/integrations/vercel-ai': '2026-06-05',
  '/docs/production/reliability': '2026-05-19',
  '/docs/production/scaling': '2026-05-19',
  '/docs/tutorials/agent-tracing': '2026-06-12',
  '/docs/tutorials/nightly-evals': '2026-06-05',
  '/docs/tutorials/rag-chatbot': '2026-06-05',
  '/docs/features/requests': '2026-06-08',
  '/docs/features/traces': '2026-06-12',
  '/docs/features/prompts': '2026-06-08',
  '/docs/features/prompts-playground': '2026-06-08',
  '/docs/features/prompt-ab': '2026-06-08',
  '/docs/features/cost-tracking': '2026-06-08',
  '/docs/features/savings': '2026-06-08',
  '/docs/features/anomalies': '2026-06-08',
  '/docs/features/security': '2026-06-04',
  '/docs/features/alerts': '2026-06-04',
  '/docs/features/webhooks': '2026-06-04',
  '/docs/features/datasets': '2026-06-04',
  '/docs/features/evals': '2026-06-04',
  '/docs/features/experiments': '2026-06-04',
  '/docs/features/annotation': '2026-06-04',
  '/docs/features/saved-filters': '2026-06-04',
  '/docs/features/export': '2026-06-04',
  '/docs/features/shares': '2026-06-04',
  '/docs/features/projects': '2026-06-04',
  '/docs/features/members-invitations': '2026-06-04',
  '/docs/features/users': '2026-06-04',
  '/docs/features/billing': '2026-06-04',
  '/docs/features/settings': '2026-06-04',
  '/docs/features/audit-logs': '2026-06-04',
  '/privacy': '2026-05-04',
  '/terms': '2026-05-04',
  '/dpa': '2026-05-04',
  '/refund': '2026-05-04',
  '/subprocessors': '2026-05-04',
}

const MARKETING_ROUTES = [
  '',
  '/pricing',
  '/self-hosting',
  '/alternatives',
  '/changelog',
  '/feedback',
  '/faq',
  '/about',
  '/integrations/openai',
  '/integrations/anthropic',
  '/integrations/gemini',
  '/llm-observability',
  '/agent-tracing',
  '/llm-cost-tracking',
  '/pricing/gpt-4o',
  '/pricing/gpt-4o-mini',
  '/pricing/claude-3-5-sonnet',
  '/pricing/gemini-2-0-flash',
  '/pricing/o3-mini',
  '/tools/llm-cost-calculator',
  '/compare',
  '/compare/langfuse',
  '/compare/helicone',
  '/compare/langsmith',
  '/compare/braintrust',
  '/compare/arize-phoenix',
] as const

const MIGRATION_ROUTES = [
  '/docs/migrate/from-langfuse',
  '/docs/migrate/from-helicone',
  '/docs/migrate/from-langsmith',
] as const

const DOCS_ROUTES = [
  '/docs',
  '/docs/quick-start',
  '/docs/cli',
  '/docs/sdk',
  '/docs/proxy',
  '/docs/otel',
  '/docs/self-host',
  '/docs/why',
  '/docs/api',
  '/docs/api/errors',
  '/docs/concepts/data-model',
  '/docs/concepts/llm-observability',
  '/docs/concepts/agent-tracing',
  '/docs/concepts/evals',
  '/docs/concepts/prompt-management',
  '/docs/integrations/langgraph',
  '/docs/integrations/langchain',
  '/docs/integrations/crewai',
  '/docs/integrations/openai-assistants',
  '/docs/integrations/bedrock',
  '/docs/integrations/flowise',
  '/docs/integrations/instructor',
  '/docs/integrations/llamaindex',
  '/docs/integrations/mcp',
  '/docs/integrations/vercel-ai',
  '/docs/production/reliability',
  '/docs/production/scaling',
  '/docs/tutorials/agent-tracing',
  '/docs/tutorials/nightly-evals',
  '/docs/tutorials/rag-chatbot',
  // NOTE: no bare '/docs/features' entry — that route does not exist (404).
  '/docs/features/requests',
  '/docs/features/traces',
  '/docs/features/prompts',
  '/docs/features/prompts-playground',
  '/docs/features/prompt-ab',
  '/docs/features/cost-tracking',
  '/docs/features/savings',
  '/docs/features/anomalies',
  '/docs/features/security',
  '/docs/features/alerts',
  '/docs/features/webhooks',
  '/docs/features/datasets',
  '/docs/features/evals',
  '/docs/features/experiments',
  '/docs/features/annotation',
  '/docs/features/saved-filters',
  '/docs/features/export',
  '/docs/features/shares',
  '/docs/features/projects',
  '/docs/features/members-invitations',
  '/docs/features/users',
  '/docs/features/billing',
  '/docs/features/settings',
  '/docs/features/audit-logs',
] as const

const LEGAL_ROUTES = [
  '/privacy',
  '/terms',
  '/dpa',
  '/refund',
  '/subprocessors',
] as const

function lastModFor(path: string): Date {
  const stamp = ROUTE_LASTMOD[path]
  // Fall back to build-time date for any route missing from the map. Logged
  // as a noisy console warning during local dev would help, but we keep the
  // file pure and just default silently.
  return stamp ? new Date(`${stamp}T00:00:00Z`) : new Date()
}

export default function sitemap(): MetadataRoute.Sitemap {
  const entries: MetadataRoute.Sitemap = [
    ...MARKETING_ROUTES.map((path) => ({
      url: `${SITE_URL}${path}`,
      lastModified: lastModFor(path),
      changeFrequency: 'weekly' as const,
      priority: path === '' ? 1.0 : 0.8,
    })),
    ...DOCS_ROUTES.map((path) => ({
      url: `${SITE_URL}${path}`,
      lastModified: lastModFor(path),
      changeFrequency: 'weekly' as const,
      priority: path === '/docs' ? 0.9 : 0.6,
    })),
    ...MIGRATION_ROUTES.map((path) => ({
      url: `${SITE_URL}${path}`,
      lastModified: lastModFor(path),
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...LEGAL_ROUTES.map((path) => ({
      url: `${SITE_URL}${path}`,
      lastModified: lastModFor(path),
      changeFrequency: 'yearly' as const,
      priority: 0.3,
    })),
  ]

  return entries
}
